db_tsdf_node:
  ros__parameters:

    # --- Input/Output & TF Parameters ---
    in_cloud: '/os_cloud_node/points'    # Input PointCloud2 topic
    odom_frame_id: 'odom'                # Odometry frame for TF lookup
    use_tf: True                         # Whether to use TF transformations

    # --- TF Mode Configuration ---
    # Defines the TF source:
    #   true:  Legacy Mode (subscribes to 'in_tf_topic').
    #   false: Generic Mode (uses the global TF2 buffer /tf).
    use_tf_topic: True
    in_tf_topic: '/gt_icp/transform'     # Topic name for Legacy Mode subscription

    # --- Point Cloud Filtering Parameters ---
    pc_downsampling: 1                   # Downsampling factor for the input cloud
    min_range: 1.5                       # Minimum sensor range (meters)
    max_range: 90.0                      # Maximum sensor range (meters)

    # --- TSDF Grid Definition ---
    # Defines the boundaries and resolution of the TSDF volume
    tdf_grid_res: 0.05                   # Voxel resolution (meters)
    tdf_max_cells: 75000.0               # Maximum allocated cells

    tdfGridSizeX_low: -100.0             # Grid X-axis minimum (meters)
    tdfGridSizeX_high: 100.0             # Grid X-axis maximum (meters)
    tdfGridSizeY_low: -100.0             # Grid Y-axis minimum (meters)
    tdfGridSizeY_high: 100.0             # Grid Y-axis maximum (meters)
    tdfGridSizeZ_low: -10.0              # Grid Z-axis minimum (meters)
    tdfGridSizeZ_high: 50.0              # Grid Z-axis maximum (meters)


    # --- Integration Kernel Parameters ---
    kernel_size:   11                     # Integration kernel size. Must be an odd number.
    occ_min_hits:  80                    # Minimum hits to consider a voxel occupied
    bins_az:       360                   # Number of azimuthal bins
    bins_el:       360                   # Number of elevation bins
    shadow_radius: 5                     # Shadow casting radius (in voxels)
    distance_mode: "L2"                  # Distance metric (e.g., "L1", "L2")